---
####################################################
# Install and configure nginx
####################################################

# Include Ansible vars
- name: include vars
  include_vars: "vars/default.yml"

- name: Install nginx
  become: yes
  apt: name=nginx state=latest

- name: Remove default page
  become: yes
  shell: rm /etc/nginx/sites-enabled/default
  ignore_errors: yes
  no_log: yes

- name: Copy nginx.conf
  become: yes
  template:
    src: "files/nginx.conf.j2"
    dest: "/etc/nginx/conf.d/nginx.conf"

- name: Check nginx configs
  shell: "/usr/sbin/nginx -t"
  register: nginx_status

- name: Service nginx restart and enable if config is ok
  service:
    name: nginx
    state: reloaded
    enabled: yes
  when: nginx_status.rc == 0

- name: Ensure nginx is running
  become: yes
  service:
    name: nginx
    state: started







